### ISSUE TITLE
Literal column name aliases for joins

### ISSUE THREAD

**Issue by leebenson** [doug-martin/goqu#107]
I'm using [sqlx](https://github.com/jmoiron/sqlx) struct scanning, to handle joins across embedded structs.

The format for winds up looking like [this example](https://snippets.aktagon.com/snippets/757-how-to-join-two-tables-with-jmoiron-sqlx), using `<table>.<col>` as a literal alias to enable multi-levels of struct parsing. 

What I'm hoping to do is compose an alias that allows `.` in the name. `.As()` doesn't work for that, since the string generated wraps identifiers with `""`, the same as `goqu.I()`.

At the moment, I'm using `.L()` to achieve the same thing:

```
goqu.L(`"table"."name" "table.name"`)
```

But it'd be nicer to do something like:

```go
t.Col(name).Alias("table.name")
```

And have the SQL generated without the wrapping quotes around each identifier (only around the whole string).

Note this is different to `.As()`, since the 'AS' statement generated is unnecessary (at least for Postgres.)

Alternatively (or additionally), since I imagine this is a relatively common use-case, what do you think about a method that implicitly aliases for this purpose?

e.g.

```go
t.Col(name).ForJoin()
```

Which would output the select as:

```sql
SELECT "table"."name" "table.name" ...
```

Thanks in advance!

**Comment by doug-martin** [comment]
@leebenson Ill have to think about this one, I'm hesitant to add the `Alias` method because I think it could easily be confused with `As` and could lead to a confusing DSL.

The `ForJoin` could work but again I think it may muddy the DSL with something that doesnt really have a corollary in SQL. Your issue around the `String` method may be a nicer solution for this but Ill have to research.

One way that I think may work I'd have to test it out could be to pass the string to `goqu.C` because it does not try to parse identifies separated by a `.`, but again this doesnt seem any cleaner than using `goqu.L` other than it would properly escape any special characters.

```go
goqu.I("schema.table.col").As(goqu.C("schema.table.col"))
// or
goqu.S("schema").Table("table").Col("col").As(goqu.C("schema.table.col"))
```

**Comment by leebenson** [comment]
Thanks @doug-martin. Given that `.C()` can essentially do the same thing as the proposed `.Alias()`, that does make aliasing redundant.

I'll close this in favour of #109. I'd be quite happy with something like:

```
col := goqu.T("A").Col("B")

// Then inside a select...
col.As(col.String())
```

👍

**Comment by sammy-tam** [comment]
Hi,

I've actually come across similar use case but except that we use the ``goqu.Select(&Struct{})`` heavily to add select all the columns defined in that struct.

Afaik there is currently no way to achieve having an alias for those auto added columns, where we have to resort to listing out all the columns e.g. 

```go
q.Select(
    goqu.I("table.col").As(goqu.C("table.col"),
    goqu.I("table.col2").As(goqu.C("table.col2")
)
```

It'd be nice to have a way to automate these for all the columns that are added via the ``goqu.Select(&Struct{})``  syntax.

Thanks!

**Comment by marshallmcmullen** [comment]
I encountered this issue as well and this was super helpful.
