### ISSUE TITLE
Dep unable to install version v7 and above

### ISSUE THREAD

**Issue by kunal-plivo** [doug-martin/goqu#139]
**Describe the bug**
We are trying to install version v8 using dep
When we run the following command

>  dep ensure -add github.com/doug-martin/goqu

version v6.1.0 is installed instead of v.8.3.1 (latest version as of today)

When we explicitly try to force a version as below

> dep ensure -add github.com/doug-martin/goqu@8.3.1

We get the following issue
```
Solving failure: No versions of github.com/doug-martin/goqu met constraints:
        v8.3.1: "github.com/doug-martin/goqu" imports "github.com/doug-martin/goqu/v8/internal/errors", which contains malformed code: no package exists at "github.com/doug-martin/goqu/v8/internal/errors"
```

Any way to install goqu version 7 or above using Dep?

**Comment by doug-martin** [comment]
I just tried this out using a couple of different ways and it does not appear to be compatible with go mod. I didn't dig too deeply but it appears to be because of the way go mod allows importing versioned packages. 

I would recommend using go mod but, I realize this isn't always feasible in an established project.

If you do find a way to make this work let me know, or better yet issue a PR with instructions added to the readme.
