### ISSUE TITLE
Embedded pointers with property names that duplicate parent struct properties.

### ISSUE THREAD

**Issue by ruzz311** [doug-martin/goqu#23]
When using an embedded struct, properties on the embedded struct that contain property names that are also in the parent struct cause `.ScanStruct()` to populate unreliably.  I assume .ScanStructs() has this issue as well.

Example: 

``` go
package "main"
// import (....)

type Dog struct {
    ID          int    `db:"id"`
    Name        string `db:"dog_name"`
    Description string `db:"dog_description"`
    Breed       string `db:"dog_breed"`
    *Fur
}

type Fur struct {
    Name        string `db:"fur_name"`
    Description string `db:"fur_description"`
    Color       string `db:"fur_color"`
    Length      string `db:"fur_length"`
}

func main() {
    pgDb, err := sql.Open("postgres", "user=postgres dbname=goqupostgres sslmode=disable")
    if err != nil {
        panic(err.Error())
    }
    db := goqu.New("postgres", pgDb)
    var dog Dog
    found, err := db.From("dog").Where(goqu.I("id").Eq(1)).ScanStruct(&dog)
    //dog's properties are not assigned consistently.
}
```

I'm assuming this has to do with the column map and/or initEmbeddedPtr found at https://github.com/doug-martin/goqu/blob/master/crud_exec.go#L221.

**Comment by FryDay** [comment]
I can't believe this hasn't been fixed. It's a major issue, and the only way I've found to fix it is to prefix the field names. In your example, you could have DogName and FurName and it would populate correctly. It's really ugly, though.

**Comment by doug-martin** [comment]
I figured out the issue, and it will be fixed in the next release. @ruzz311 you were partially right, it was an issue with how I was accessing fields when doing reflection. 

I [`reflect.go`](https://github.com/doug-martin/goqu/blob/5cfb4d4e2dcb08343d43eae38606d06126124bb7/internal/util/reflect.go#L124) I was accessing the field by name, when the names were duplicated it was using the first one found. I instead had to change it to `reflect.FieldByIndex` and keep track of the field index when creating the column map.

I added tests for both an embedded struct and pointer with different db tag names and it should work now. I should note if you have two fields with the same name without a `db` tag it will fall back to which one occurred first.
