### ISSUE TITLE
Invalid generated SQL for Where class when using goqu.C().IsNull() with sqlserver dialect

### ISSUE THREAD

**Issue by phillipCouto** [doug-martin/goqu#239]
**Describe the bug**
The SQL generated for an `IsNull()` expression in the Where clause is incorrect when using the SQL Dialect.

**To Reproduce**
```sql
CREATE TABLE Test(
  id int NOT NULL,
  val varchar(255)
);

INSERT INTO Test VALUES (1, NULL);
```

```go
d := goqu.Dialect("sqlserver")

qry, _, _ := d.Select(goqu.Count("*")).From(goqu.T("Test")).Where(goqu.C("val").IsNull()).Prepared(false).ToSQL()

var count int
db.QueryRow(qry).Scan(&count)
log.Println(count)
```

I expect the log to print `1` but it will print `0` and if you print the query you will see:

> SELECT COUNT(*) FROM "Test" WHERE ("val" = NULL)

**Expected behavior**

Query should be:

> SELECT COUNT(*) FROM "Test" WHERE ("val" IS NULL)

**Dialect:**

- [ ] postgres 
- [ ] mysql
- [ ] sqlite3 
- [x] sqlserver

**Comment by phillipCouto** [comment]
This is also the same when using `goqu.Ex{"val": nil}` or `goqu.Ex{"val": goqu.Op{"is":nil}}`

**Comment by vlanse** [comment]
The problem is because sqlserver dialect implementation is as follows:
```
...
exp.IsOp:             []byte("="),
...
```
As I remember this was done to mimic lack of support for boolean data type in SQL Server, but as I see now, this was initially incorrect. Probably we should use `IS` and just fail when IsTrue is used - because it's natural for SQL Server
