### ISSUE TITLE
Allow adapters to use different order  of clauses when building query

### ISSUE THREAD

**Issue by yzzyx** [doug-martin/goqu#32]
I'm creating an adapter for sqlserver, and I've run into a couple of places where building the query occurs in a different order than postgres/mysql/sqlite.

Examples:
- limit and offset order is swapped
postgres, sqlite, etc: 
`SELECT * FROM entry ORDER BY test LIMIT 1 OFFSET 5`
sqlserver: 
`SELECT * FROM entry ORDER BY test OFFSET 5 ROWS FETCH NEXT 1 ROWS ONLY`

- the "returning" clause comes before VALUES.
postgres, sqlite, etc: 
`INSERT INTO entry (col1, col2) VALUES (1, 2) RETURN col1`
sqlserver: 
`INSERT INTO entry (col1, col2) OUTPUT col1 VALUES (1, 2)`

In the limit/offset-case I made a hack to support it, but my suggestion is to somehow let the adapter
specify the order a query should be built in (and possibly access the different clauses "out-of-order" if necessary).

My suggested implementation would be to pass the whole 'me.clauses' to the adapter in selectSqlWriteTo/ToUpdateSql/etc.
`DefaultAdapter` would then process the clauses exactly as it's done today, but it would
allow for example the sqlserver-adapter to build it's queries in a different order.

What's your take on this? Any ideas/suggestions?

**Comment by doug-martin** [comment]
Well I think that may be more complex than expected because the Dataset has a reference to the actual adapter instance (e.g Postgres, MySQL vs Default Adapter). If each derived adapter does not  shadow the SQL generation method, then the `DefaultAdapters` method would be called, which would cause it to call the default implementation of all the methods rather than the derived classes implementation. 

It may be better if we could somehow let the adapter specify order but still allow the `Dataset` to call the adapter instance directly so any methods that are shadowed in the implementation are still called directly. 

I think one option may be to allow each adapter to maintain a slice of fragment types that the Dataset then uses to call the methods in the correct order.

```golang

//in the adapter 
selectFragmentOrdering : []string{"SELECT_DISTINCT", "SELECT", "FROM", /*and the rest of the types*/}


//in the dataset selectSqlWriteTo

for frag := range me.adapter.selectFragmentOrdering {
	switch frag {
	case "SELECT_DISTINCT":
		if err := me.adapter.SelectDistinctSql(buf, me.clauses.SelectDistinct); err != nil {
			return err
		}
	case "SELECT":
		if err := me.adapter.SelectSql(buf, me.clauses.Select); err != nil {
			return err
		}
	case "FROM":
		if err := me.adapter.FromSql(buf, me.clauses.From); err != nil {
			return err
		}
        //implement the rest of the cases you can find them in dataset_select.go#366 selectSqlWriteTo
	}
}
```

**Comment by doug-martin** [comment]
Support for overriding the default clause ordering has been added in `v7` you can [take a look here](https://github.com/doug-martin/goqu/blob/master/sql_dialect_options.go#L463) but to override that in an adapter it should be a simple as overriding that property with your own order.
