### ISSUE TITLE
UUID: Nil

### ISSUE THREAD

**Issue by efureev** [doug-martin/goqu#87]
How can I change one Value by other Value on execute query?
Example: 
UUID: https://github.com/satori/go.uuid/blob/master/uuid.go#L72 
It's must be `NULL` in sql but it - `00000000-0000-0000-0000-000000000000`.
How can I replace this struct on my Value on execute query?

**Comment by deitrix** [comment]
It's unclear what you're trying to achieve without a code snippet. `uuid.Nil` isn't nil in a go sense, it's simply the zero value of a uuid. You shouldn't be using it if you want your uuid to be `NULL` in the database. Instead, you should use something like `sql.NullString`, or a nil string pointer.

**Comment by doug-martin** [comment]
Closing for now. Without a good example Im unsure how to help. If you can post a small code snippet Ill reopen and try to help.

**Comment by vesperusiak** [comment]
Hi, so I run into this using https://github.com/google/uuid and I think it's a bug, let me explain:

let's assume I have this structure in code:
```
User struct {
		ID                uuid.UUID      `db:"id"`
                 // other stuff
}
```
and I try to make an insert statement:
```
user := &User{}
q := goqu.Insert("users").Rows(user)
sql, _, _ := q.ToSQL()
```

Then it will write `00000000-0000-0000-0000-000000000000` into the sql because user.ID == uuid.Nil and uuid.Value() returns string value of user.ID which is `00000000-0000-0000-0000-000000000000` for uuid.Nil. This behavior is good since RFC says 
```
The nil UUID is special form of UUID that is specified to have all
   128 bits set to zero.
```
(https://tools.ietf.org/html/rfc4122#section-4.1.7)

But we still need somehow to add NULL to a database and I think that using `sql.NullString` as proposed earlier is not the best idea because it requires for a developer to add additional layer in the code.

So when using uuid without goqu I passed a uuid pointer to sqlx and if it was nil sqlx converted it into `NULL`. But when You pass a pointer like this into goqu it will panic on `ToSQL()` line precisely here https://github.com/doug-martin/goqu/blob/751dbc6747e6cdcb0bf146b2817e783cb19e4dea/sqlgen/expression_sql_generator.go#L106 because uuid does not have a pointer receiver on the Value method. I think that not having a pointer receiver here is also ok since even types like NullString use second variable for a `nil` state instead of pointer receiver so the best but not perfect solution would be to catch that case and convert a nil pointer to `NULL`. WDYT?

**Comment by deitrix** [comment]
I agree that using the following struct:
```go
type User struct {
	ID *uuid.UUID `db:"id"`
}
```

Should not yield a panic when `ID` is `nil`. It comes down to the `UUID` type implementing the `driver.Valuer` interface, but as a value receiver instead of a pointer receiver:

```go
// Value implements the driver.Valuer interface.
func (u UUID) Value() (driver.Value, error) {
	...
}
```

For `goqu` to work with nil UUID values, the implementation would need to have a pointer receiver:
```go
func (u *UUID) Value() (driver.Value, error) {
	if u == nil {
		return nil, nil
	}
	...
}
```

I should point out that `github.com/satori/go.uuid` has a `NullUUID` type which works much in the same way that `NullString` works.
